package files

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// sha256("hello\n") — the reference value produced by `printf 'hello\n' | sha256sum`.
const helloDigest = "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03"

func writeTemp(t *testing.T, content string) string {
	t.Helper()
	f := filepath.Join(t.TempDir(), "payload.tar.gz")
	if err := os.WriteFile(f, []byte(content), 0o600); err != nil {
		t.Fatalf("write temp file: %v", err)
	}
	return f
}

func TestFileSHA256(t *testing.T) {
	got, err := FileSHA256(writeTemp(t, "hello\n"))
	if err != nil {
		t.Fatalf("FileSHA256: %v", err)
	}
	if got != helloDigest {
		t.Fatalf("FileSHA256 = %s, want %s", got, helloDigest)
	}
}

func TestFileSHA256MissingFile(t *testing.T) {
	if _, err := FileSHA256(filepath.Join(t.TempDir(), "nope")); err == nil {
		t.Fatal("FileSHA256 on a missing file should fail")
	}
}

func TestVerifyFileSHA256(t *testing.T) {
	f := writeTemp(t, "hello\n")

	if err := VerifyFileSHA256(f, helloDigest); err != nil {
		t.Fatalf("matching digest should verify, got: %v", err)
	}
	// Uppercase and surrounding whitespace are accepted.
	if err := VerifyFileSHA256(f, "  "+strings.ToUpper(helloDigest)+"  "); err != nil {
		t.Fatalf("uppercase digest should verify, got: %v", err)
	}
	// A single flipped nibble must be rejected.
	bad := "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be04"
	if err := VerifyFileSHA256(f, bad); err == nil {
		t.Fatal("mismatching digest must be rejected")
	}
}

func TestParseSHA256File(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{"bare digest", helloDigest, helloDigest},
		{"sha256sum format", helloDigest + "  3panel-v2.0.1-linux-amd64.tar.gz", helloDigest},
		{"single space", helloDigest + " 3panel.tar.gz", helloDigest},
		{"trailing newline", helloDigest + "\n", helloDigest},
		{"uppercase", strings.ToUpper(helloDigest), helloDigest},
		{"leading comments and blanks", "# generated by CI\n\n  \n" + helloDigest + "  f.tar.gz\n", helloDigest},
		{"picks first valid line", "not-a-digest\n" + helloDigest + "  f.tar.gz\n", helloDigest},
		{"empty", "", ""},
		{"only comments", "# nothing here\n\n", ""},
		{"too short", "abc123", ""},
		{"not hex", strings.Repeat("z", 64), ""},
		{"wrong length 63", strings.Repeat("a", 63), ""},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := ParseSHA256File(tc.content); got != tc.want {
				t.Fatalf("ParseSHA256File(%q) = %q, want %q", tc.content, got, tc.want)
			}
		})
	}
}

// The realistic end-to-end shape: a checksum file that names the package, and a
// package that matches it.
func TestVerifyAgainstParsedChecksumFile(t *testing.T) {
	f := writeTemp(t, "hello\n")
	checksumFile := helloDigest + "  3panel-v2.0.1-linux-amd64.tar.gz\n"

	expected := ParseSHA256File(checksumFile)
	if expected == "" {
		t.Fatal("failed to parse digest from checksum file")
	}
	if err := VerifyFileSHA256(f, expected); err != nil {
		t.Fatalf("package should verify against its checksum file, got: %v", err)
	}
}
